name: sunbook
description: A new Flutter project.

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    develop:
      app:
        name: "sunbook-dev"

      android:
        applicationId: "com.example.sunbook.stg"

      ios:
        bundleId: "com.example.apple"

    staging:
      app:
        name: "sunbook-stg"

      android:
        applicationId: "com.example.sunbook.dev"
      ios:
        bundleId: "com.example.banana"

    production:
      app:
        name: "sunbook-prod"

      android:
        applicationId: "com.example.sunbook"

      ios:
        bundleId: "com.example.apple"

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_flavorizr: ^2.1.3
  get: ^4.6.5
  objectbox: ^1.5.0
  flutter_launcher_icons: ^0.9.3
  getwidget: ^3.0.1
  flutter_hooks: ^0.18.5+1
  date_time_picker: ^2.1.0
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_storage: ^10.3.1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/sunbook-prod.jpg


